### ISSUE TITLE
X-Plane update 10.35b1

### ISSUE THREAD

**Issue by e00rasmussen** [ksgy/x-economy#10]
Hi guys.. thanks for a fantastic job with this plugin.. love it.. 

After yesterdays update of x-plane Plugin stops LUA .. ??? 
something about DataRef issues .. ???

Are you aware of any changes that could effect x-economy?

[000899] FlyWithLua Info: Start loading script file Resources/plugins/FlyWithLua/Scripts/FSE.lua
[000900] FlyWithLua Error: The DataRef "fse/status/connected" does not exist.
[000901] FlyWithLua Error: The DataRef "fse/status/flying" does not exist.
[000902] FlyWithLua Error: The DataRef "fse/status/leasetime" does not exist.
[000903] FlyWithLua Error: The DataRef "fse/status/flighttime" does not exist.
[000904] FlyWithLua Info: Finished loading script file Resources/plugins/FlyWithLua/Scripts/FSE.lua
[000905] FlyWithLua Error: The error seems to be inside of script file Resources/plugins/FlyWithLua/Scripts/FSE.lua

Using V1.8.1

Kindly Erik Denmark

**Comment by ansorg** [comment]
running "X-Plane 10.35b1 (64-bit build 103501) compiled on Feb 10 2015 16:50:49" on Win8.1/64 here and LUA scripts do work the same as before. Something on your end? Check yor log.txt ...

Oh, and LUA is not essential for the FSE addon (this is Python), the LUA scripts are just complementary 

good luck

**Comment by e00rasmussen** [comment]
I do not see x-economy in the plugin pulldown.. like i used to??? so your saying its the .py file that is my problem?

**Comment by ansorg** [comment]
Yes. Do you still have those files? And the Python Interface active?

\X-Plane 10\Resources\plugins\PythonScripts\
07.02.2015  15:54            54.992 PI_xfse.py
07.02.2015  16:04            43.967 PI_xfse.pyc
18.02.2015  22:37            43.896 PythonInterfaceLog.txt
18.02.2015  22:26            61.606 PythonInterfaceOutput.txt
16.02.2015  19:51                14 x-economy.ini

**Comment by e00rasmussen** [comment]
Have just removed the plugin.. and LUA script.. now my restarting sim .. but the python consol complains about something about sockets? Does that ring any bell?

and yes I did have everything running.. but noticed that x-economy.ini was missing.. somehow

**Comment by e00rasmussen** [comment]
YAY!!!!!   it appears as my Python was having problems... did a uninstall and reinstalled Python.. 2.7.9 x64 .. and NOW i see x-economy in my plugin menu... yay.. now i'll test the LUA script

Volla!!!   ITS working agian... thanks for your feedback.. 

Kindly ONE HAPPY man.
