### ISSUE TITLE
[XFSE|Nfo] Invalid script

### ISSUE THREAD

**Issue by moreorlessgit** [ksgy/x-economy#7]
I'm on a mac and followed directions EXACTLY. It is still not working. Here is the log and output.

LOG:
+++ LOGGING STARTED +++
PythonInterface 2.73.06 (SDK 2.10) - Sandy Barbour 2005
PythonInterface.ini file found
Before Py_Initialize()
After Py_Initialize()
Python Version 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] running on the darwin platform
Before Modules Init
Using path below for script path
/Volumes/Macintosh HD/Users/terkeygirl/Library/Application Support/Steam/steamapps/common/X-Plane 10/Resources/plugins/PythonScripts
After Modules Init
Searching for Standard Scripts
Script 'PI_xfse.py' successfully loaded.

OUTPUT:
[XFSE|Nfo] BTN Login
[XFSE|Nfo] Logincheck
[XFSE|Nfo] Login was not successful
[XFSE|Nfo] Invalid script
[XFSE|dbg] Client window closed

**Comment by ansorg** [comment]
Is this with 1.8.1? The New Version is not yet allowed on the FSE server!

**Comment by moreorlessgit** [comment]
Yes sir, actually! I'll see if using the old version helps, Thanks!!!!

**Comment by moreorlessgit** [comment]
Its working now. Thanks again!

**Comment by tanin** [comment]
I'm getting exactly the same message on x-palne 9.7 mac osx, Python 2.7.9 PythonInterface 2.73.02

[XFSE|Nfo] BTN Login
[XFSE|Nfo] Logincheck
[XFSE|Nfo] Login was not successful
[XFSE|Nfo] Invalid script
[XFSE|dbg] Client window closed

**Comment by e00rasmussen** [comment]
me too.. x-plane 10.35 final pc win 7 pro. python 2.7.9



–
E.Rasmussen Mailbox

**Comment by ksgy** [comment]
Which version of the plugin are you using?

**Comment by tanin** [comment]
I tried both 1.8.1 and 1.8.0 and getting the same result.

**Comment by ksgy** [comment]
Updated the link to the script, see this page:
https://sites.google.com/site/fseoperationsguide/getting-started/using-the-fse-client/x-plane

**Comment by tanin** [comment]
Thanks, it works.
